[theme]

# Base colors can be 'light' or 'dark'
base = "light"

# Primary color for your app, specified as a hex or named CSS color
primaryColor = "#5c7680"

# Background color for your app
backgroundColor = "#ffffff"

# Secondary background color for your app
secondaryBackgroundColor = "#f4f4f4"

# Text color for your app
textColor = "#546163"

# Font for your app, choose between "sans serif", "serif", and "monospace"
font = "sans serif"